server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Compression GZIP pour les performances
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Gérer intelligemment le cache pour éviter l'erreur de hash des fichiers JS
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Redirection SPA (Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Les assets (CSS, images) peuvent être cachés pendant un an
    location ~* \.(?:css|jpg|svg|png|woff2?|eot|ttf|otf|mp4|webm|ico)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }

    # Fichiers Javascript : On force le type MIME strict
    location ~* \.js$ {
        types { application/javascript js; }
        default_type application/javascript;
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }

    # Proxy pour le Backend Spring Boot
    location /api/ {
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
